spring.application.name=api-gateway
server.port=8080

jwt.secret=${JWT_SECRET}

# Auth Service - public
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8088
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Telemedicine Service - not public
spring.cloud.gateway.routes[1].id=telemedicine-service
spring.cloud.gateway.routes[1].uri=http://telemedicine-service:8087
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/sessions/**

# Patient Service
spring.cloud.gateway.routes[2].id=patient-service
spring.cloud.gateway.routes[2].uri=http://patient-service:8085
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/patients/**

