version: '3.8'

services:

  api-gateway:
    build: ./healthcare-platform/services/api-gateway # access Dockerfile of this service
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:8088
      - TELEMEDICINE_SERVICE_URL=http://telemedicine-service:8087
    depends_on: # Ensures these services start before gateway
      - auth-service
      - telemedicine-service

  auth-service:
    build: ./healthcare-platform/services/auth-service # access Dockerfile of this service
    ports:
      - "8088:8088"
    environment:
      - MONGO_URI=${MONGO_URI_AUTH}
      - PORT=8088
      - JWT_SECRET=${JWT_SECRET}

  telemedicine-service:
    build: ./healthcare-platform/services/telemedicine-service # access Dockerfile of this service
    ports:
      - "8087:8087"
    environment:
      - MONGO_URI=${MONGO_URI_TELEMEDICINE}
      - PORT=8087
      - JWT_SECRET=${JWT_SECRET}

  doctor-service:
    build: ./healthcare-platform/services/doctor-service
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=${MONGO_URI_DOCTOR}
      - PORT=8083
      - JWT_SECRET=${JWT_SECRET}
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8082
      - PATIENT_SERVICE_URL=http://patient-service:8081
    depends_on:
      - auth-service

  appointment-service:
    build: ./healthcare-platform/services/appointment-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=${MONGO_URI_APPOINTMENT}
      - PORT=8082
      - JWT_SECRET=${JWT_SECRET}
      - DOCTOR_SERVICE_URL=http://doctor-service:8083
      - DOCTOR_SERVICE_MOCK_ENABLED=false
      - NOTIFICATION_SERVICE_URL=http://notification-service:8086
      - NOTIFICATION_SERVICE_MOCK_ENABLED=true
    depends_on:
      - auth-service
      - doctor-service
