spring.application.name=auth-service

logging.level.org.springframework.cloud.gateway=DEBUG

spring.mongodb.uri=${MONGO_URI}
server.port=${PORT:8088}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}