apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-service
  namespace: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doctor-service
  template:
    metadata:
      labels:
        app: doctor-service
    spec:
      containers:
        - name: doctor-service
          image: doctor-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: MONGO_URI_DOCTOR
            - name: PORT
              value: "8083"
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: JWT_SECRET
            - name: APPOINTMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: APPOINTMENT_SERVICE_URL
            - name: PATIENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: healthcare-config
                  key: PATIENT_SERVICE_URL
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: healthcare
spec:
  type: ClusterIP
  selector:
    app: doctor-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      name: http
